apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
  namespace: tenant-host-ns
  labels:
    obegron.github.io/secret-sync-enabled: "true"
  annotations:
    obegron.github.io/secret-sync-targets: '[{"kind":"cluster","namespace":"shared-runtime"}]'
    obegron.github.io/delete-policy: delete
stringData:
  username: appuser
  password: supersecret
