apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
  namespace: tenant-host-ns
  labels:
    obegron.github.io/sync-to-vcluster: "true"
  annotations:
    obegron.github.io/vcluster-name: tenant-a-dev01
    obegron.github.io/vcluster-namespace: app-runtime
    obegron.github.io/delete-policy: delete
stringData:
  username: appuser
  password: supersecret
