apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret-vcluster-only
  namespace: tenant-host-ns
  labels:
    obegron.github.io/secret-sync-enabled: "true"
  annotations:
    obegron.github.io/secret-sync-targets: '[{"kind":"vcluster","vcluster":"tenant-a-dev01","namespace":"app-runtime"}]'
    obegron.github.io/delete-policy: delete
type: Opaque
stringData:
  username: appuser
  password: supersecret
