apiVersion: v1
kind: Secret
metadata:
  name: namespace1-secret1
  namespace: tenant-host-ns
  labels:
    obegron.github.io/secret-sync-enabled: "true"
  annotations:
    obegron.github.io/secret-sync-targets: >-
      [
        {"kind":"cluster","namespace":"shared-runtime-a","name":"secret1"},
        {"kind":"cluster","namespace":"shared-runtime-b","name":"secret1"}
      ]
    obegron.github.io/delete-policy: delete
type: Opaque
stringData:
  username: appuser
  password: supersecret
