apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret-many-namespaces
  namespace: tenant-host-ns
  labels:
    obegron.github.io/secret-sync-enabled: "true"
  annotations:
    obegron.github.io/secret-sync-targets: >-
      [
        {"kind":"cluster","namespace":"shared-runtime-a"},
        {"kind":"cluster","namespace":"shared-runtime-b"}
      ]
    obegron.github.io/delete-policy: delete
type: Opaque
stringData:
  username: appuser
  password: supersecret
