apiVersion: v1
kind: Secret
metadata:
  name: vcluster-kubeconfigs
  namespace: vcluster-secret-sync-system
type: Opaque
stringData:
  tenant-a-dev01.kubeconfig: |
    # kubeconfig content for target vcluster
    apiVersion: v1
    kind: Config
    clusters: []
    contexts: []
    current-context: ""
    users: []
