apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../rbac/serviceaccount.yaml
  - ../rbac/rbac-role.yaml
  - ../rbac/rbac-binding.yaml
  - deployment.yaml
