apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../rbac/serviceaccount.yaml
  - ../rbac/clusterrole.yaml
  - ../rbac/clusterrolebinding.yaml
  - deployment.yaml
