{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vcluster-secret-sync-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vcluster-secret-sync-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vcluster-secret-sync-controller.fullname" . }}
{{- end }}
