apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vcluster-secret-sync-controller
subjects:
  - kind: ServiceAccount
    name: vcluster-secret-sync-controller
    namespace: vcluster-secret-sync-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vcluster-secret-sync-controller
