{{- if .Values.rbac.create }}
{{- if eq (lower .Values.controller.syncMode) "pull" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "secret-sync-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "secret-sync-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "secret-sync-controller.fullname" . }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "secret-sync-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "secret-sync-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "secret-sync-controller.fullname" . }}
{{- end }}
{{- end }}
