{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secret-sync-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
